name: Simple CI Demo

on:
  push:
    branches:
      - main

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout-repository
      uses: action/checkout@v4

      - name: Run build step
        run: echo "building app"

        - name: Run test step
          run: echo "Running tests"

        - name: Finish
          run: echo "CI pipeline finished"
